import { Router, type IRouter, type Request, type Response } from 'express';
import { and, eq } from 'drizzle-orm';
import { db, auditLogsTable, centersTable, plansTable, programsTable, usersTable, reviewsTable } from '@workspace/db';
import { clearSession, createSession, currentUser, hashPassword, verifyPassword } from '../lib/auth';

const router:IRouter=Router();
const id=(prefix:string)=>`${prefix}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
async function auth(req:Request,res:Response){const user=await currentUser(req);if(!user){res.status(401).json({error:'UNAUTHENTICATED'});return null}return user;}
function managerOnly(user:any,res:Response){if(user.role!=='manager'){res.status(403).json({error:'FORBIDDEN'});return false}return true;}
function sameCenter(user:any,centerId:string,res:Response){if(user.centerId!==centerId){res.status(403).json({error:'CENTER_ACCESS_DENIED'});return false}return true;}

router.post('/auth/login',async(req,res)=>{const username=String(req.body?.username||'').trim().toLowerCase();const password=String(req.body?.password||'');const row=(await db.select().from(usersTable).where(eq(usersTable.username,username)).limit(1))[0];if(!row||!row.active||!(await verifyPassword(password,row.passwordHash)))return res.status(401).json({error:'INVALID_LOGIN'});await createSession(row.id,res);res.json({user:{...row,passwordHash:undefined}});});
router.post('/auth/logout',async(req,res)=>{await clearSession(req,res);res.json({ok:true});});

router.get('/bootstrap',async(req,res)=>{const user=await auth(req,res);if(!user)return;const center=(await db.select().from(centersTable).where(eq(centersTable.id,user.centerId)).limit(1))[0];const baseUsers=await db.select({id:usersTable.id,centerId:usersTable.centerId,name:usersTable.name,username:usersTable.username,role:usersTable.role,active:usersTable.active,supervisorId:usersTable.supervisorId,level:usersTable.level,enrollmentDate:usersTable.enrollmentDate}).from(usersTable).where(eq(usersTable.centerId,user.centerId));const visibleStudents=user.role==='manager'?baseUsers.filter(u=>u.role==='student'):user.role==='supervisor'?baseUsers.filter(u=>u.id===user.id||u.supervisorId===user.id):baseUsers.filter(u=>u.id===user.id);const visibleIds=new Set(visibleStudents.filter(u=>u.role==='student').map(u=>u.id));const users=user.role==='manager'?baseUsers:[...baseUsers.filter(u=>u.id===user.id),...baseUsers.filter(u=>u.role==='supervisor'&&user.role==='supervisor'&&u.id===user.id),...visibleStudents.filter(u=>u.role==='student')];const plansAll=await db.select().from(plansTable).where(eq(plansTable.centerId,user.centerId));const plans=user.role==='manager'?plansAll:plansAll.filter(p=>visibleIds.has(p.studentId)||(user.role==='student'&&p.studentId===user.id));const programsAll=await db.select().from(programsTable).where(eq(programsTable.centerId,user.centerId));const programs=user.role==='manager'?programsAll:programsAll.filter(p=>visibleIds.has(p.studentId)||(user.role==='student'&&p.studentId===user.id));const auditLogs=await db.select().from(auditLogsTable).where(eq(auditLogsTable.centerId,user.centerId));const reviewsAll=await db.select().from(reviewsTable).where(eq(reviewsTable.centerId,user.centerId));const reviews=user.role==='manager'?reviewsAll:reviewsAll.filter(r=>visibleIds.has(r.studentId)||(user.role==='student'&&r.studentId===user.id));res.json({currentUser:{...user,passwordHash:undefined},center,users,plans,programs,auditLogs,reviews});});

router.post('/users',async(req,res)=>{const user=await auth(req,res);if(!user||!managerOnly(user,res))return;const body=req.body||{};const centerId=user.centerId;if(!body.name||!body.username||!body.password||!['student','supervisor'].includes(body.role))return res.status(400).json({error:'INVALID_USER'});const username=String(body.username).trim().toLowerCase();const exists=(await db.select({id:usersTable.id}).from(usersTable).where(eq(usersTable.username,username)).limit(1))[0];if(exists)return res.status(409).json({error:'USERNAME_TAKEN'});const newId=id('u');await db.insert(usersTable).values({id:newId,centerId,name:String(body.name).trim(),username,passwordHash:await hashPassword(String(body.password)),role:body.role,active:true,supervisorId:body.role==='student'?(body.supervisorId||null):null,level:body.level||null,enrollmentDate:body.enrollmentDate||null});res.status(201).json({id:newId});});
router.patch('/users/:id',async(req,res)=>{const user=await auth(req,res);if(!user||!managerOnly(user,res))return;const target=(await db.select().from(usersTable).where(eq(usersTable.id,req.params.id)).limit(1))[0];if(!target||!sameCenter(user,target.centerId,res))return;const body=req.body||{};await db.update(usersTable).set({name:body.name??target.name,active:body.active??target.active,supervisorId:body.supervisorId===undefined?target.supervisorId:body.supervisorId,level:body.level===undefined?target.level:body.level,enrollmentDate:body.enrollmentDate===undefined?target.enrollmentDate:body.enrollmentDate}).where(eq(usersTable.id,target.id));res.json({ok:true});});
router.delete('/users/:id',async(req,res)=>{const user=await auth(req,res);if(!user||!managerOnly(user,res))return;const target=(await db.select().from(usersTable).where(eq(usersTable.id,req.params.id)).limit(1))[0];if(!target||!sameCenter(user,target.centerId,res))return;if(target.role==='manager')return res.status(400).json({error:'CANNOT_DELETE_MANAGER'});await db.delete(usersTable).where(eq(usersTable.id,target.id));await db.delete(programsTable).where(eq(programsTable.studentId,target.id));await db.delete(plansTable).where(eq(plansTable.studentId,target.id));await db.insert(auditLogsTable).values({id:id('a'),centerId:user.centerId,actorUserId:user.id,action:'حذف حساب',targetUserId:target.id,details:target.name,createdAt:new Date()});res.json({ok:true});});

router.post('/plans',async(req,res)=>{const user=await auth(req,res);if(!user||!managerOnly(user,res))return;const b=req.body||{};const student=(await db.select().from(usersTable).where(and(eq(usersTable.id,String(b.studentId)),eq(usersTable.centerId,user.centerId))).limit(1))[0];if(!student||student.role!=='student')return res.status(400).json({error:'INVALID_STUDENT'});const newId=id('p');await db.insert(plansTable).values({id:newId,centerId:user.centerId,studentId:student.id,date:String(b.date),type:String(b.type),surah:String(b.surah||''),ayahFrom:Number(b.ayahFrom),ayahTo:Number(b.ayahTo),pageFrom:Number(b.pageFrom),pageTo:Number(b.pageTo),requiredAmount:Number(b.requiredAmount),actualAmount:Number(b.actualAmount||0),evaluationPages:Number(b.evaluationPages||1),status:b.status||'pending',notes:b.notes||null,evaluation:b.evaluation||null,evaluations:b.evaluations||[]});res.status(201).json({id:newId});});
router.patch('/plans/:id',async(req,res)=>{const user=await auth(req,res);if(!user)return;const target=(await db.select().from(plansTable).where(eq(plansTable.id,req.params.id)).limit(1))[0];if(!target||!sameCenter(user,target.centerId,res))return;if(user.role==='student')return res.status(403).json({error:'FORBIDDEN'});if(user.role==='supervisor'){const student=(await db.select().from(usersTable).where(eq(usersTable.id,target.studentId)).limit(1))[0];if(!student||student.supervisorId!==user.id)return res.status(403).json({error:'NOT_ASSIGNED'});const program=(await db.select().from(programsTable).where(eq(programsTable.studentId,target.studentId)).limit(1))[0];if(!program?.supervisorCanEditPlans && Object.keys(req.body||{}).some(k=>['date','requiredAmount','evaluationPages','pageFrom','pageTo','surah','ayahFrom','ayahTo'].includes(k)))return res.status(403).json({error:'PLAN_EDIT_DISABLED'});}const b=req.body||{};await db.update(plansTable).set({date:b.date===undefined?target.date:String(b.date),type:b.type===undefined?target.type:String(b.type),surah:b.surah===undefined?target.surah:String(b.surah),ayahFrom:b.ayahFrom===undefined?target.ayahFrom:Number(b.ayahFrom),ayahTo:b.ayahTo===undefined?target.ayahTo:Number(b.ayahTo),pageFrom:b.pageFrom===undefined?target.pageFrom:Number(b.pageFrom),pageTo:b.pageTo===undefined?target.pageTo:Number(b.pageTo),requiredAmount:b.requiredAmount===undefined?target.requiredAmount:Number(b.requiredAmount),actualAmount:b.actualAmount===undefined?target.actualAmount:Number(b.actualAmount),evaluationPages:b.evaluationPages===undefined?target.evaluationPages:Number(b.evaluationPages),status:b.status===undefined?target.status:String(b.status),notes:b.notes===undefined?target.notes:b.notes,evaluation:b.evaluation===undefined?target.evaluation:b.evaluation,evaluations:b.evaluations===undefined?target.evaluations:b.evaluations}).where(eq(plansTable.id,target.id));res.json({ok:true});});
router.put('/programs/:studentId',async(req,res)=>{const user=await auth(req,res);if(!user||!managerOnly(user,res))return;const student=(await db.select().from(usersTable).where(and(eq(usersTable.id,req.params.studentId),eq(usersTable.centerId,user.centerId))).limit(1))[0];if(!student||student.role!=='student')return res.status(400).json({error:'INVALID_STUDENT'});const b=req.body||{};const exists=(await db.select().from(programsTable).where(eq(programsTable.studentId,student.id)).limit(1))[0];const values={studentId:student.id,centerId:user.centerId,pageStates:b.pageStates||{},active:b.active??true,defaultMemorizationPages:Number(b.defaultMemorizationPages||1),defaultRevisionPages:Number(b.defaultRevisionPages||4),reviewEvaluationPages:Number(b.reviewEvaluationPages||2),supervisorCanEditPlans:b.supervisorCanEditPlans??true,supervisorCanAdjustSchedule:b.supervisorCanAdjustSchedule??true,delayPolicy:b.delayPolicy||'shift_remaining',reviewCycleDays:Number(b.reviewCycleDays||7),commitmentWeight:Number(b.commitmentWeight??15),commitmentTargetPercent:Number(b.commitmentTargetPercent??70)};if(exists)await db.update(programsTable).set(values).where(eq(programsTable.studentId,student.id));else await db.insert(programsTable).values(values);res.json({ok:true});});

router.post('/reviews',async(req,res)=>{const user=await auth(req,res);if(!user)return;const b=req.body||{};const student=(await db.select().from(usersTable).where(and(eq(usersTable.id,String(b.studentId)),eq(usersTable.centerId,user.centerId))).limit(1))[0];if(!student||student.role!=='student')return res.status(400).json({error:'INVALID_STUDENT'});if(user.role==='supervisor'&&student.supervisorId!==user.id)return res.status(403).json({error:'NOT_ASSIGNED'});if(user.role==='student')return res.status(403).json({error:'FORBIDDEN'});const review={id:id('r'),centerId:user.centerId,studentId:student.id,periodStart:String(b.periodStart),periodEnd:String(b.periodEnd),evaluatedPages:Number(b.evaluatedPages||1),reviewStrength:Math.max(0,Math.min(100,Number(b.reviewStrength||0))),score:Math.max(0,Math.min(100,Number(b.score||b.reviewStrength||0))),notes:b.notes?String(b.notes):null,createdAt:new Date()};await db.insert(reviewsTable).values(review);res.status(201).json(review);});

router.post('/schedule/reconcile',async(req,res)=>{const user=await auth(req,res);if(!user)return;const studentId=String(req.body?.studentId||'');const planId=String(req.body?.planId||'');const mode=String(req.body?.mode||'manual');const pageDelta=Number(req.body?.pageDelta||0);const student=(await db.select().from(usersTable).where(and(eq(usersTable.id,studentId),eq(usersTable.centerId,user.centerId))).limit(1))[0];if(!student||student.role!=='student')return res.status(400).json({error:'INVALID_STUDENT'});if(user.role==='supervisor'){if(student.supervisorId!==user.id)return res.status(403).json({error:'NOT_ASSIGNED'});const program=(await db.select().from(programsTable).where(eq(programsTable.studentId,studentId)).limit(1))[0];if(!program?.supervisorCanAdjustSchedule)return res.status(403).json({error:'SCHEDULE_ADJUST_DISABLED'});}else if(user.role!=='manager')return res.status(403).json({error:'FORBIDDEN'});const anchor=(await db.select().from(plansTable).where(and(eq(plansTable.id,planId),eq(plansTable.studentId,studentId),eq(plansTable.centerId,user.centerId))).limit(1))[0];if(!anchor||pageDelta===0)return res.json({ok:true,changed:0});const future=(await db.select().from(plansTable).where(and(eq(plansTable.centerId,user.centerId),eq(plansTable.studentId,studentId),eq(plansTable.type,'memorization')))).filter(p=>p.date>anchor.date).sort((a,b)=>a.date.localeCompare(b.date));const addDays=(date:string,n:number)=>{const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};let changed=0;if(mode==='shift_remaining'){const deltaDays=pageDelta<0?Math.ceil(Math.abs(pageDelta)): -Math.floor(Math.abs(pageDelta));for(const p of future){await db.update(plansTable).set({date:addDays(p.date,deltaDays),notes:`${p.notes||''} | تصحيح تلقائي للبرنامج`}).where(eq(plansTable.id,p.id));changed++;}}else if(mode==='compress_next_week'){let remaining=Math.abs(pageDelta);const targets=future.filter(p=>p.date<=addDays(anchor.date,7));for(const p of targets){if(remaining<=0)break;const add=Math.max(1,Math.ceil(remaining/Math.max(1,targets.length)));await db.update(plansTable).set({requiredAmount:p.requiredAmount+add,notes:`${p.notes||''} | ضغط البرنامج بسبب فرق ${pageDelta}`}).where(eq(plansTable.id,p.id));remaining-=add;changed++;}}await db.insert(auditLogsTable).values({id:id('a'),centerId:user.centerId,actorUserId:user.id,action:'تصحيح البرنامج الزمني',targetUserId:studentId,details:`${mode} / فرق الصفحات ${pageDelta} / عناصر معدلة ${changed}`,createdAt:new Date()});res.json({ok:true,changed});});

router.patch('/center',async(req,res)=>{const user=await auth(req,res);if(!user||!managerOnly(user,res))return;const name=String(req.body?.name||'').trim();if(!name)return res.status(400).json({error:'INVALID_NAME'});await db.update(centersTable).set({name}).where(eq(centersTable.id,user.centerId));res.json({ok:true});});
router.post('/manager/transfer',async(req,res)=>{const user=await auth(req,res);if(!user||!managerOnly(user,res))return;const target=(await db.select().from(usersTable).where(eq(usersTable.id,String(req.body?.newManagerId||''))).limit(1))[0];if(!target||target.centerId!==user.centerId||target.role!=='supervisor'||!target.active)return res.status(400).json({error:'INVALID_MANAGER_TARGET'});await db.update(usersTable).set({role:'supervisor'}).where(eq(usersTable.id,user.id));await db.update(usersTable).set({role:'manager',supervisorId:null}).where(eq(usersTable.id,target.id));await db.insert(auditLogsTable).values({id:id('a'),centerId:user.centerId,actorUserId:user.id,action:'نقل صلاحية مدير المركز',targetUserId:target.id,details:`إلى ${target.name}`,createdAt:new Date()});await clearSession(req,res);await createSession(target.id,res);res.json({ok:true});});

export default router;
