import {useState} from 'react';
import {StoreProvider,useStore} from './lib/store';
import ManagerDashboard from './pages/ManagerDashboard';
import SupervisorDashboard from './pages/SupervisorDashboard';
import StudentDashboard from './pages/StudentDashboard';
import {BookOpen,LogIn} from 'lucide-react';
import {Shell} from './components/layout/Shell';

function Login(){const {login}=useStore();const [u,setU]=useState('admin');const [p,setP]=useState('1234');const [err,setErr]=useState('');const submit=async()=>{setErr('');if(!await login(u,p))setErr('بيانات الدخول غير صحيحة أو الحساب غير مفعل')};return <div className="min-h-screen flex items-center justify-center bg-background p-4"><div className="w-full max-w-md"><div className="text-center mb-7"><div className="mx-auto w-16 h-16 rounded-2xl bg-primary text-primary-foreground flex items-center justify-center shadow-lg"><BookOpen size={32}/></div><h1 className="text-3xl font-serif font-bold text-primary mt-4">منصة متابعة حفظ القرآن</h1><p className="text-muted-foreground mt-1">نظام إدارة الحفظ والمراجعة والتقييم</p></div><div className="bg-card border rounded-2xl shadow-sm p-6 space-y-4"><div><label className="text-sm font-medium">اسم المستخدم</label><input className="w-full mt-1 rounded-lg border bg-background px-3 py-2" value={u} onChange={e=>setU(e.target.value)}/></div><div><label className="text-sm font-medium">كلمة المرور</label><input type="password" className="w-full mt-1 rounded-lg border bg-background px-3 py-2" value={p} onChange={e=>setP(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')submit()}}/></div>{err&&<div className="text-sm text-destructive bg-destructive/10 rounded-lg p-3">{err}</div>}<button className="w-full bg-primary text-primary-foreground rounded-lg py-2.5 font-bold flex items-center justify-center gap-2" onClick={submit}><LogIn size={18}/>تسجيل الدخول</button><div className="text-xs text-muted-foreground border-t pt-4 space-y-1"><p>تجربة المركز الأول — مدير: <b>admin</b> / <b>1234</b></p><p>تجربة المركز الثاني — مدير: <b>admin2</b> / <b>1234</b></p><p>مشرف: <b>mohammed</b> / <b>1234</b> — طالب: <b>omar</b> / <b>1234</b></p></div></div></div></div>}
function AppContent(){const {currentUser}=useStore();if(!currentUser)return <Login/>;return <Shell>{currentUser.role==='manager'?<ManagerDashboard/>:currentUser.role==='supervisor'?<SupervisorDashboard/>:<StudentDashboard/>}</Shell>}
export default function App(){return <StoreProvider><AppContent/></StoreProvider>}
